# Generated by Django 3.1.7 on 2021-03-08 06:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('longprofile', '0003_follow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Follow2',
        ),
    ]
