# Generated by Django 3.1.7 on 2021-03-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longprofile', '0006_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection',
            field=models.IntegerField(default=0),
        ),
    ]
