# Generated by Django 3.1.7 on 2021-03-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longprofile', '0008_createevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='createevent',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
