# Generated by Django 3.1.7 on 2021-03-20 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('longprofile', '0015_auto_20210319_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createappoinment',
            name='enquired_person',
        ),
        migrations.RemoveField(
            model_name='createappoinment',
            name='user',
        ),
        migrations.CreateModel(
            name='CreateAppoinment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('dateandtime', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('enquired_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snder', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
