# Generated by Django 3.1.7 on 2021-03-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longprofile', '0016_auto_20210320_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='createappoinment2',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
