# Generated by Django 3.2 on 2021-04-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_group_groupmembers_groupmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
