# Generated by Django 3.2 on 2021-04-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_groupmessage_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
