# Generated by Django 3.2 on 2021-04-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_groupmessage_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='delete',
            new_name='receiver_delete',
        ),
        migrations.AddField(
            model_name='message',
            name='sender_delete',
            field=models.BooleanField(default=False),
        ),
    ]
