# Generated by Django 3.2 on 2021-04-28 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_auto_20210427_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='seen',
        ),
        migrations.CreateModel(
            name='GroupSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groupmessage')),
            ],
        ),
    ]
