# Generated by Django 3.2 on 2021-04-29 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20210428_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupseen',
            name='group',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='chat.group'),
            preserve_default=False,
        ),
    ]
